### ISSUE TITLE
How to change the tag qbitunregistered makes within qbittorrent

### ISSUE THREAD

**Issue by NoahBK** [Kha-kis/qbitunregistered#5]
When the script gets done and finds a problem torrent(s) it adds a tag within qbit called unregistered:crossseeding and I looked through the config file and couldn't find what is making the tags. I could be dumb. I probably am. But, I would love to change the tag to something else. Thanks.

![C4SoQwI](https://github.com/Kha-kis/qbitunregistered/assets/35641648/f71d672b-c7fd-4b0a-9afa-6fd19106453d)

**Comment by Kha-kis** [comment]
It is hard coded by default. I can make this a configuration option.

It would take the same tag and append crossseeding if the torrent is cross seeded.

Is there an alternative option there you would like to see?

**Comment by NoahBK** [comment]
Nothing specific, no. Just having the option to change it would be nice. I appreciate you responding back so quickly. Love qbitunregistered. It saves so much time.

**Comment by Kha-kis** [comment]
Glad to hear you have been enjoying the project.

I have updated the project to allow custom tags.

please see the new options in the config example and I hope this suits your needs!

If all is well please let me know and will mark this issue closed.

**Comment by NoahBK** [comment]
Looks good to me! Thank you!
